config/routes.rb
Rails.application.routes.draw do
  root  'top#index'
  post "income_values/new/(/:name)" => "income_values#new"
  post "fixed_values/new/(/:name)" => "fixed_values#new"
  post "change_values/new/(/:name)" => "change_values#new"

  get "balance" => "balance#top"
  post "balance/show(/:name)" => "balance#show"
  post "balance/show_year(/:name)" => "balance#show_year"

  resources :incomes
  resources :fixeds
  resources :changes
  resources :income_values
  resources :fixed_values
  resources :change_values
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/change.rb
class Change < ApplicationRecord
  has_many :change_values, dependent: :destroy

  validates :name, presence: true
end

app/models/change_value.rb
class ChangeValue < ApplicationRecord
  validates :change_id, presence: true
end

app/models/fixed.rb
class Fixed < ApplicationRecord
  has_many :fixed_values, dependent: :destroy

  validates :name, presence: true
end

app/models/fixed_value.rb
class FixedValue < ApplicationRecord

  validates :fixed_id, presence: true
end

app/models/income.rb
class Income < ApplicationRecord
  has_many :income_values, dependent: :destroy

  validates :name, presence: true
end

app/models/income_value.rb
class IncomeValue < ApplicationRecord

  validates :income_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth


  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/balance_controller.rb
class BalanceController < ApplicationController
  def top
  end

  def show
    @year_month = params[:year_month] + "-1"
    @incomes = Income.order(created_at: :asc)
    @fixeds = Fixed.order(created_at: :asc)
    @changes = Change.order(created_at: :asc)

    #収入計算
    @income_values = IncomeValue.where(year_month: @year_month)
    @income_value_total = 0
    @income_values.each do |income_value|
      @income_value_total += income_value.value
    end

    #固定費計算
    @fixed_values = FixedValue.where(year_month: @year_month)
    @fixed_value_total = 0
    @fixed_values.each do |fixed_value|
      @fixed_value_total += fixed_value.value
    end
    
    #変動費計算
    @change_values = ChangeValue.where(year_month: @year_month)
    @change_value_total = 0
    @change_values.each do |change_value|
      @change_value_total += change_value.value
    end
    
    #収支差
    @balance_difference = @income_value_total - (@fixed_value_total + @change_value_total)

  end

  def show_year
    year = params[:year]
    @year = year
    months = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"]
    year_months = months.map do |month|
      year+ "-"+ month +"-01"
    end

    puts year_months

    #年度の収入配列を作成
    i=0
    total = [nil,nil,nil,nil,nil,nil,nil,nil,nil,nil,nil,nil]
    year_months.each do |year_month|
      income_values = IncomeValue.where(year_month: year_month)
      if income_values.present?
        total[i] = cal_income_total(income_values)
      end
      i += 1
    end
    @income_value_totals = total

    #年度の固定費配列を作成
    i = 0
    total = [nil,nil,nil,nil,nil,nil,nil,nil,nil,nil,nil,nil]
    year_months.each do |year_month|
      fixed_values = FixedValue.where(year_month: year_month)
      if fixed_values.present?
        total[i] = cal_fixed_total(fixed_values)
      end
      i+=1
    end
    @fixed_value_totals = total

    #年度の変動費配列を作成
    i = 0
    total = [nil,nil,nil,nil,nil,nil,nil,nil,nil,nil,nil,nil]
    year_months.each do |year_month|
      change_values = ChangeValue.where(year_month: year_month)
      if change_values.present?
      total[i] = cal_change_total(change_values)
      end
      i+=1
    end
    @change_value_totals = total

    #年度の収支結果を計算
    @balance_differences = [nil,nil,nil,nil,nil,nil,nil,nil,nil,nil,nil,nil]
    0.upto(11) do |i|
      if @income_value_totals[i].present?
        @balance_differences[i] = @income_value_totals[i] - (@fixed_value_totals[i]+ @change_value_totals[i])
      end
    end
  end
  
  #収入トータル計算
  def cal_income_total(income_values)
    income_value_total = 0
    income_values.each do |income_value|
      income_value_total += income_value.value
    end
    income_value_total
  end

  #固定費トータル計算
  def cal_fixed_total(fixed_values)
    fixed_value_total = 0
    fixed_values.each do |fixed_value|
      fixed_value_total += fixed_value.value
    end
    fixed_value_total
  end

  #変動費トータル計算
  def cal_change_total(change_values)
    change_value_total = 0
    change_values.each do |change_value|
      change_value_total += change_value.value
    end
    change_value_total
  end
end

app/controllers/changes_controller.rb
class ChangesController < ApplicationController
  before_action :set_change, only: [:show, :edit, :update, :destroy]

  def index
    @changes = Change.order(created_at: :asc)
	end
 
	def show
	end
 
	def new
    @change = Change.new()
	end
 
	def edit
	end
 
  def create
		@change = Change.new(change_params)
		if @change.save
			redirect_to changes_path
		else
			render :new
		end
	end

	def update
		if @change.update(change_params)
			redirect_to changes_path
		else
			render :new
		end
	end
 
  def destroy
		@change.destroy
		redirect_to changes_path
	end

  private

  def set_change
    @change = Change.find(params[:id])
  end

  def change_params
    params.require(:change).permit(:name, :description)
  end

end

app/controllers/fixeds_controller.rb
class FixedsController < ApplicationController
  before_action :set_fixed, only: [:show, :edit, :update, :destroy]

  def index
    @fixeds = Fixed.order(created_at: :asc)
	end
 
	def show
	end
 
	def new
    @fixed = Fixed.new()
	end
 
	def edit
	end
 
  def create
		@fixed = Fixed.new(fixed_params)
		if @fixed.save
			redirect_to fixeds_path
		else
			render :new
		end
	end

	def update
		if @fixed.update(fixed_params)
			redirect_to fixeds_path
		else
			render :new
		end
	end
 
  def destroy
		@fixed.destroy
		redirect_to fixeds_path
	end

  private

  def set_fixed
    @fixed = Fixed.find(params[:id])
  end

  def fixed_params
    params.require(:fixed).permit(:name, :description)
  end

end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: [:show, :edit, :update, :destroy]
  
  def index
    @incomes = Income.order(created_at: :asc)
	end
 
	def show
	end
 
	def new
    @income = Income.new()
	end
 
	def edit
	end
 
  def create
		@income = Income.new(income_params)
		if @income.save
			redirect_to incomes_path
		else
			render :new
		end
	end

	def update
		if @income.update(income_params)
			redirect_to incomes_path
		else
			render :new
		end
	end
 
  def destroy
		@income.destroy
		redirect_to incomes_path
	end

  private

  def set_income
    @income = Income.find(params[:id])
  end

  def income_params
    params.require(:income).permit(:name, :description)
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/balance_helper.rb
module BalanceHelper
end

app/helpers/change_values_helper.rb
module ChangeValuesHelper
end

app/helpers/changes_helper.rb
module ChangesHelper
end

app/helpers/fixed_values_helper.rb
module FixedValuesHelper
end

app/helpers/fixeds_helper.rb
module FixedsHelper
end

app/helpers/income_values_helper.rb
module IncomeValuesHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/balance/show.html.erb
<div class="body">

<div class="title">
 <div class="main-title"><%= link_to "kakevo", root_path %></div>
</div>


<div class="balance-i"><%= @year_month %> 月次収支確認 </div>
<div class="memory1">収入</div>
<% if @income_values.present? %>
<table>
  <thead>
      <tr>
          <th>科目名</th>
          <th>値</th>
          <th>備考</th>
      </tr>
  </thead>
  <tbody>
      <% @income_values.each do |income_value| %>
        <tr>
         <td><%= @incomes.find(income_value.income_id).name %></td>
         <td style= "text-align: right"><%= income_value.value %>円</td>
         <td><%= income_value.description %></td>
        </tr>
      <% end %>
      <tr>
         <td><b>収入合計</b></td>
         <td style= "text-align: right"><b><%= @income_value_total %>円</b></td>
         <td></td>
      </tr>
  </tbody>
</table>

<% else %>
  <p>登録されている収入がありません</p>
<% end %>

<div class="memory2">固定費</div>
<% if @fixed_values.present? %>
<table>
  <thead>
      <tr>
          <th>科目名</th>
          <th>値</th>
          <th>備考</th>
      </tr>
  </thead>
  <tbody>
      <% @fixed_values.each do |fixed_value| %>
        <tr>
            <td><%= @fixeds.find(fixed_value.fixed_id).name %></td>
            <td style="text-align: right"><%= fixed_value.value %>円</td>
            <td><%= fixed_value.description %></td>
        </tr>
      <% end %>
      <tr>
         <td><b>固定費合計</b></td>
         <td style= "text-align: right"><b><%= @fixed_value_total %>円</b></td>
         <td></td>
      </tr>
  </tbody>
</table>

<% else %>
     <P>登録されている固定費がありません</p>
<% end %>

<div class="memory3">変動費</div>
<% if @change_values.present? %>
<table>
  <thead>
      <tr>
          <th>科目名</th>
          <th>値</th>
          <th>備考</th>
      </tr>
  </thead>
  <tbody>
      <% @change_values.each do |change_value| %>
          <tr>
             <td><%= @changes.find(change_value.change_id).name %></td>
             <td style= "text-align: right"><%= change_value.value %>円</td>
             <td><%= change_value.description %></td>
          </tr>
      <% end %>
      <tr>
          <td><b>変動費合計</b></td>
          <td style="text-align: right"><b><%= @change_value_total %>円</b></td>
          <td></td>
      </tr>
  </tbody>
</table>


<table>
<tbody>
<tr>
     <div class="memory4">収支差</div>
    <td><b><%= @balance_difference %>円</b></td>
    <td></td>
</tr>
</tbody>
</table>


<% else %>
     <P>登録されている変動費がありません。</p>
<% end %>
</div>

app/views/balance/show_year.html.erb
<div class="body">
<div class="title">
 <div class="main-title"><%= link_to "kakevo", root_path %></div>
</div>

<div class="balance-i"><%= @year %>年 年間収支確認</div>
<table>
        <tr>
          <th>年月</th>
          <th>収入合計値</th>
          <th>固定費合計値</th>
          <th>変動費合計値</th>
          <th>収支(収入-費用)結果</th>
        </tr>
      <% month = 1 %>
      <% 0.upto(11) do |i| %>
        <% if @income_value_totals[i].present? %>
            <tr>
            <td><%= @year %>年<%= i+1 %>月</td>
            <td><%= @income_value_totals[i]%>円</td>
            <td><%= @fixed_value_totals[i]%>円</td>
            <td><%= @change_value_totals[i]%>円</td>
            <td><%= @balance_differences[i]%>円</td>
            </tr>
        <% end %>
      <% end %>
</table>
</div>

app/views/balance/top.html.erb
<div class="body">
<div class="title">
 <div class="main-title"><%= link_to "kakevo", root_path %></div>
</div>


<div class="balance-i">月次収支確認</div>
<div class="balance-r"><%= form_tag({controller: :balance, action: :show}, {method: :post}) do %>
<input type="month" name="year_month">
<input type="submit">
<% end %>
</div>

<div class="balance-i">年間収支確認</div>
<div class="balance-r"><%= form_tag({controller: :balance, action: :show_year}, {method: :post}) do %>
    <input type="hidden" name="year" >
        <select name="year">
          <% 2010.upto(2050) do |n| %>
              <option value=<%= n.to_s %>><%= n %></option>
          <% end %>
        </select>
    <input type="submit">
</div>
<% end %>
</div>

app/views/top/index.html.erb
<div class="body">

  <div class="title">
   <div class="main-title">kakevo</div>
   <div class="sub-title">~シンプルな家計簿~</div>
  </div>

  <div class="contents">

    <div class="contents-one">
     <div class="name1">科目設定</div>
     <div class="income"><%= link_to "収入科目設定", incomes_path %></div>
     <div class="fixed"><%= link_to "固定費科目設定", fixeds_path %></div>
     <div class="changes"><%= link_to "変動費科目設定", changes_path %></div>
    </div>

    <div class="contents-two">
      <div class="name1">収支登録</div>
      <div class="income"><%= link_to "収入金額登録", income_values_path %></div>
      <div class="fixed"><%= link_to "固定費金額登録", fixed_values_path %></div>
      <div class="changes"><%= link_to "変動費金額登録", change_values_path %></div>
    </div>

    <div class="contents-three">
      <div class="name1">収支確認</div>
      <div class="balance"><%= link_to "収支確認画面", balance_path %></div>
    </div>

  </div>
</div> 