config/routes.rb
Rails.application.routes.draw do
  root  'top#index'
  post "income_values/new/(/:name)" => "income_values#new"
  post "fixed_values/new/(/:name)" => "fixed_values#new"
  post "change_values/new/(/:name)" => "change_values#new"

  get "balance" => "balance#top"
  post "balance/show(/:name)" => "balance#show"
  post "balance/show_year(/:name)" => "balance#show_year"

  resources :incomes
  resources :fixeds
  resources :changes
  resources :income_values
  resources :fixed_values
  resources :change_values
end

app/models/change.rb
class Change < ApplicationRecord
  has_many :change_values, dependent: :destroy

  validates :name, presence: true
end

app/models/form/change_form.rb
class Form::ChangeForm < Form::Base
	attr_accessor :change_values

	def initialize(attributes = {})
    super attributes
		changes = Change.order(created_at: :asc)
		self.change_values = changes.map { |change| ChangeValue.new(change_id: change.id) } unless change_values.present?
  end

	def change_values_attributes=(attributes)
    self.change_values = attributes.map do |_, change_value_attributes|
      Form::ChangeValues.new(change_value_attributes).tap { |v| puts v}
    end

  end

	def valid?
		valid_change_values = self.change_values.map(&:valid?).all?
		super && valid_change_values
	end

	def save
		return false unless valid?
		ChangeValue.transaction {
			self.change_values.select.each { |change_value|
				a1 = ChangeValue.new(:change_id => change_value.change_id,
					:year_month => change_value.year_month,
					:value => change_value.value,
					:description => change_value.description)
				a1.save!
			 }
		}
		true
	end

	def target_change_values
		self.change_values.select { |v| '*' }
	end

end

app/controllers/changes_controller.rb
class ChangesController < ApplicationController
  before_action :set_change, only: [:show, :edit, :update, :destroy]

  def index
    @changes = Change.order(created_at: :asc)
	end
 
	def show
	end
 
	def new
    @change = Change.new()
	end
 
	def edit
	end
 
  def create
		@change = Change.new(change_params)
		if @change.save
			redirect_to changes_path
		else
			render :new
		end
	end

	def update
		if @change.update(change_params)
			redirect_to changes_path
		else
			render :new
		end
	end
 
  def destroy
		@change.destroy
		redirect_to changes_path
	end

  private

  def set_change
    @change = Change.find(params[:id])
  end

  def change_params
    params.require(:change).permit(:name, :description)
  end

end

app/helpers/changes_helper.rb
module ChangesHelper
end

app/views/changes/_form.html.erb
<div class="change-index"><%= link_to "変動費科目一覧に戻る", changes_path %></div>
<table>
 <tr>
	 <th><%= form.label :name, "名称" %></th>
	 <td><%= form.text_field :name %></td>
 </tr>
 <tr>
	<th><%= form.label :description, "説明" %></th>
	<td><%= form.text_field :description %></td>
 </tr>
</table>

app/views/changes/edit.html.erb
<div class="body">

<div class="title">
 <div class="main-title"><%= link_to "kakevo", root_path %></div>
</div>


<div class="change-new">変動費科目編集</div>
<%= form_for @change do |form| %>
	<%= render "form", form: form %>
	<div class="register"><%= form.submit "編集" %></div>
<% end %>

app/views/changes/index.html.erb
<div class="body">

<div class="title">
 <div class="main-title"><%= link_to "kakevo", root_path %></div>
</div>

<div class="change-index"><%= "変動費科目一覧" %>
</div>
<div class="change-new"><%= link_to "変動費科目の新規登録", new_change_path %>
</div>
<% if @changes.present? %>
<table>
	<thead>
		<tr>
			<th>科目名</th>
			<th>備考</th>
      <th>操作</th>
		</tr>
	</thead>
	<tbody>
		<% @changes.each do |change| %>
			<tr>
				<td><%= change.name %></td>
				<td><%= change.description %></td>
        <td>
				<%= link_to "編集", edit_change_path(change.id) %>
        <%= link_to "削除", change_path(change.id), method: :delete %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

<% else %>
	<p>登録されている収入科目がありません。</p>
<% end %>
</div>

app/views/changes/new.html.erb
<div class="body">

<div class="title">
 <div class="main-title"><%= link_to "kakevo", root_path %></div>
</div>
<div class="change-new">変動費科目登録</div>
<%= form_for @change do |form| %>
	<%= render "form", form: form %>
	<div class="register"><%= form.submit "登録" %></div>
<% end %>
</div>

app/views/changes/show.html.erb
<h2>変動費科目の詳細</h2>

<%= link_to "編集", edit_change_path(:id) %>
<%= link_to "変動費科目一覧へ戻る", changes_path %>

<table>

	<tr>
    <th>名称</th>
    <td><%= @change.name %></td>
  </tr>

	<tr>
		<th>説明</th>
		<td><%= @change.description %></td>
	</tr>
</table>