config/routes.rb
Rails.application.routes.draw do
  root  'top#index'
  post "income_values/new/(/:name)" => "income_values#new"
  post "fixed_values/new/(/:name)" => "fixed_values#new"
  post "change_values/new/(/:name)" => "change_values#new"

  get "balance" => "balance#top"
  post "balance/show(/:name)" => "balance#show"
  post "balance/show_year(/:name)" => "balance#show_year"

  resources :incomes
  resources :fixeds
  resources :changes
  resources :income_values
  resources :fixed_values
  resources :change_values
end

app/models/fixed.rb
class Fixed < ApplicationRecord
  has_many :fixed_values, dependent: :destroy

  validates :name, presence: true
end

app/models/form/fixed_form.rb
class Form::FixedForm < Form::Base
	attr_accessor :fixed_values

	def initialize(attributes = {})
    super attributes
		fixeds = Fixed.order(created_at: :asc)
		self.fixed_values = fixeds.map { |fixed| FixedValue.new(fixed_id: fixed.id) } unless fixed_values.present?
  end

	def fixed_values_attributes=(attributes)
    self.fixed_values = attributes.map do |_, fixed_value_attributes|
      Form::FixedValues.new(fixed_value_attributes).tap { |v| puts v}
    end

  end

	def valid?
		valid_fixed_values = self.fixed_values.map(&:valid?).all?
		super && valid_fixed_values
	end

	def save
		return false unless valid?
		FixedValue.transaction {
			self.fixed_values.select.each { |fixed_value|
				a1 = FixedValue.new(:fixed_id => fixed_value.fixed_id,
					:year_month => fixed_value.year_month,
					:value => fixed_value.value,
					:description => fixed_value.description)
				a1.save!
			 }
		}
		true
	end

	def target_fixed_values
		self.fixed_values.select { |v| '*' }
	end

end

app/controllers/fixeds_controller.rb
class FixedsController < ApplicationController
  before_action :set_fixed, only: [:show, :edit, :update, :destroy]

  def index
    @fixeds = Fixed.order(created_at: :asc)
	end
 
	def show
	end
 
	def new
    @fixed = Fixed.new()
	end
 
	def edit
	end
 
  def create
		@fixed = Fixed.new(fixed_params)
		if @fixed.save
			redirect_to fixeds_path
		else
			render :new
		end
	end

	def update
		if @fixed.update(fixed_params)
			redirect_to fixeds_path
		else
			render :new
		end
	end
 
  def destroy
		@fixed.destroy
		redirect_to fixeds_path
	end

  private

  def set_fixed
    @fixed = Fixed.find(params[:id])
  end

  def fixed_params
    params.require(:fixed).permit(:name, :description)
  end

end

app/helpers/fixeds_helper.rb
module FixedsHelper
end

app/views/fixeds/_form.html.erb
<div class="fixed-index"><%= link_to "固定費科目一覧に戻る", fixeds_path %>
<table>
 <tr>
	 <th><%= form.label :name, "名称" %></th>
	 <td><%= form.text_field :name %></td>
 </tr>
 <tr>
	<th><%= form.label :description, "説明" %></th>
	<td><%= form.text_field :description %></td>
 </tr>
</table>

app/views/fixeds/edit.html.erb
<div class="body">

<div class="title">
 <div class="main-title"><%= link_to "kakevo", root_path %></div>
</div>


<div class="fixed-new">固定費科目編集</div>
<%= form_for @fixed do |form| %>
	<%= render "form", form: form %>
	<div class="register"><%= form.submit "編集" %></div>
<% end %>

app/views/fixeds/index.html.erb
<div class="body">

<div class="title">
 <div class="main-title"><%= link_to "kakevo", root_path %></div>
</div>
<div class="fixed-index"><%= "固定費科目一覧" %>
</div>
<div class="fixed-new"><%= link_to "固定費科目の新規登録", new_fixed_path %>
</div>
 
<% if @fixeds.present? %>
<table>
	<thead>
		<tr>
			<th>科目名</th> 
			<th>備考</th>
      <th>操作</th>
		</tr>
	</thead>
	<tbody>
		<% @fixeds.each do |fixed| %>
			<tr>
				<td><%= fixed.name %></td>
				<td><%= fixed.description %></td>
        <td>
				<%= link_to "編集", edit_fixed_path(fixed.id) %>
        <%= link_to "削除", fixed_path(fixed.id), method: :delete %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

<% else %>
	<p>登録されている収入科目がありません。</p>
<% end %>
</div>

app/views/fixeds/new.html.erb
<div class="body">

<div class="title">
 <div class="main-title"><%= link_to "kakevo", root_path %></div>
</div>

<div class="fixed-new">固定費科目登録</div>
<%= form_for @fixed do |form| %>
	<%= render "form", form: form %>
	<div class="register"><%= form.submit "登録" %></div>
<% end %>
</div>

app/views/fixeds/show.html.erb
<h2>固定費科目の詳細</h2>

<%= link_to "編集", edit_fixed_path(:id) %>
<%= link_to "収入科目一覧へ戻る", fixeds_path %>

<table>

	<tr>
    <th>名称</th>
    <td><%= @fixed.name %></td>
  </tr>

	<tr>
		<th>説明</th>
		<td><%= @fixed.description %></td>
	</tr>
</table>