config/routes.rb
Rails.application.routes.draw do
  root  'top#index'
  post "income_values/new/(/:name)" => "income_values#new"
  post "fixed_values/new/(/:name)" => "fixed_values#new"
  post "change_values/new/(/:name)" => "change_values#new"

  get "balance" => "balance#top"
  post "balance/show(/:name)" => "balance#show"
  post "balance/show_year(/:name)" => "balance#show_year"

  resources :incomes
  resources :fixeds
  resources :changes
  resources :income_values
  resources :fixed_values
  resources :change_values
end

app/models/form/income_form.rb
class Form::IncomeForm < Form::Base
	attr_accessor :income_values

	def initialize(attributes = {})
    super attributes
		incomes = Income.order(created_at: :asc)
		self.income_values = incomes.map { |income| IncomeValue.new(income_id: income.id) } unless income_values.present?
  end

	def income_values_attributes=(attributes)
    self.income_values = attributes.map do |_, income_value_attributes|
      Form::IncomeValues.new(income_value_attributes).tap { |v| puts v}
    end

  end

	def valid?
		valid_income_values = self.income_values.map(&:valid?).all?
		super && valid_income_values
	end

	def save
		return false unless valid?
		IncomeValue.transaction {
			self.income_values.select.each { |income_value|
				a1 = IncomeValue.new(:income_id => income_value.income_id,
					:year_month => income_value.year_month,
					:value => income_value.value,
					:description => income_value.description)
				a1.save!
			 }
		}
		true
	end

	def target_income_values
		self.income_values.select { |v| '*' }
	end

end

app/models/income.rb
class Income < ApplicationRecord
  has_many :income_values, dependent: :destroy

  validates :name, presence: true
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: [:show, :edit, :update, :destroy]
  
  def index
    @incomes = Income.order(created_at: :asc)
	end
 
	def show
	end
 
	def new
    @income = Income.new()
	end
 
	def edit
	end
 
  def create
		@income = Income.new(income_params)
		if @income.save
			redirect_to incomes_path
		else
			render :new
		end
	end

	def update
		if @income.update(income_params)
			redirect_to incomes_path
		else
			render :new
		end
	end
 
  def destroy
		@income.destroy
		redirect_to incomes_path
	end

  private

  def set_income
    @income = Income.find(params[:id])
  end

  def income_params
    params.require(:income).permit(:name, :description)
  end

end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/incomes/_form.html.erb
<div class="income-index"><%= link_to "収入科目一覧に戻る", incomes_path %></div>
<table>
 <tr>
	 <th><%= form.label :name, "名称" %></th>
	 <td><%= form.text_field :name %></td>
 </tr>
 <tr>
	<th><%= form.label :description, "説明" %></th>
	<td><%= form.text_field :description %></td>
 </tr>
</table>

app/views/incomes/edit.html.erb
<div class="body">

<div class="title">
 <div class="main-title"><%= link_to "kakevo", root_path %></div>
</div>

<div class="income-new">収入科目編集</div>
<%= form_for @income do |form| %>
	<%= render "form", form: form %>
	<div class="register"><%= form.submit "編集" %></div>
<% end %>
</div>

app/views/incomes/index.html.erb
<div class="body">

  <div class="title">
   <div class="main-title"><%= link_to "kakevo", root_path %></div>
	</div>


  <div class="income-index"><%= "収入科目一覧" %>
	</div>
  <div class="income-new"><%= link_to "収入科目の新規登録", new_income_path %>
	</div>
 
   <% if @incomes.present? %>
    <table>
	    <thead>
		    <tr>
			   <th>科目名</th>
			   <th>備考</th>
         <th>操作</th>
		    </tr>
	    </thead>
	    <tbody>
		    <% @incomes.each do |income| %>
			    <tr>
				   <td><%= income.name %></td>
				   <td><%= income.description %></td>
           <td>
				   <%= link_to "編集", edit_income_path(income.id) %>
           <%= link_to "削除", income_path(income.id), method: :delete %>
				   </td>
			    </tr>
		    <% end %>
	    </tbody>
    </table>
    <% else %>
	   <p>登録されている収入科目がありません。</p>
    <% end %>
	
</div>

app/views/incomes/new.html.erb
<div class="body">

<div class="title">
 <div class="main-title"><%= link_to "kakevo", root_path %></div>
</div>

<div class="income-new">収入科目登録</div>
<%= form_for @income do |form| %>
	<%= render "form", form: form %>
	<div class="register"><%= form.submit "登録" %></div>
<% end %>
</div>

app/views/incomes/show.html.erb
<h2>収入科目の詳細</h2>

<%= link_to "編集", edit_income_path %>
<%= link_to "収入科目一覧へ戻る", incomes_path %>

<table>

	<tr>
    <th>名称</th>
    <td><%= @income.name %></td>
  </tr>

	<tr>
		<th>説明</th>
		<td><%= @income.description %></td>
	</tr>
</table>